# Generated by Django 3.2 on 2021-05-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cl', models.CharField(max_length=100)),
                ('prenom_cl', models.CharField(max_length=100)),
                ('email_cl', models.EmailField(max_length=254)),
                ('sexe_cl', models.CharField(max_length=50)),
                ('phone_cl', models.CharField(max_length=50)),
                ('statut_cl', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10000)),
            ],
        ),
    ]
