# Generated by Django 3.2 on 2021-05-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionClient.client')),
            ],
        ),
    ]
