# Generated by Django 3.2 on 2021-05-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionClient', '0003_client_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Souscription',
        ),
    ]
